name: lint
on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm lint
